### ISSUE TITLE
Remove the SNAPSHOT from the standard test suite

### ISSUE THREAD

**Issue by leiicamundi** [camunda/c8-multi-region#111]
The `SNAPSHOT` is almost always failing, the result for the PRs is that the test suite is almost always broken due to the SNAPSHOT.

Instead of having it running for renovate and PRs suchs as https://github.com/camunda/c8-multi-region/pull/110, we could just trigger the `SNAPSHOT` tests in the scheduled actions.

It will allow us to test against non moving parts only.

What do you think @Langleu?

**Comment by Langleu** [comment]
`scheduled` and `workflow_dispatch` but yes we can do that.
Personally, since we don't have automerge due to security restrictions I don't see much of an advantage since it doesn't hinder you from merging but if it helps with a better overview, then why not.
Agree snapshot is currently not ideal but that's being worked on as the monorepo is aligning their CI to prevent that.
